<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

// class for audio column
$audioClass = 'third';

//build media contents
$thismedia=array('transcript'=>false,'audio'=>false,'pdf'=>false);
if ($embedMedia && $itemMedia):
    foreach ($itemMedia as $media):
        $thismediatype=$media->value('dcterms:type');
        if ($thismediatype=='viewable_transcript'):
            $thismedia['transcript']=$media->render();
        elseif ($thismediatype=='audio'):
            $thismedia['audio'][$media->title()]=$media->render();
        elseif ($thismediatype=='pdf_transcript'):
            $thismedia['pdf']=$media->originalUrl();
        endif;
    endforeach;
endif; ?>
<nav class="breadcrumbs"></nav>
<div class="row">
    <div class="full">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
        <?php $this->trigger('view.show.before'); ?>
    </div>
</div>
<?php
  if (!$thismedia['transcript']):
    $audioClass = 'no-transcript';
  endif;
?>

<div class="row">
    <div id="itemproperties" class="<?php echo $audioClass; ?>">
        <?php if ($thismedia['audio']):
          foreach ($thismedia['audio'] as $audioTitle => $audio):
            if (count($thismedia['audio']) > 1):
              echo $audioTitle;
            endif;
            echo $audio;
          endforeach;
        endif;?>
        <div id="properties">
            <div class="property">
                <?php echo $item->displayValues(); ?>
            </div>
        </div>
        <?php if ($thismedia['pdf'] && !$thismedia['transcript']):?>
            <div class="row">
                <div id="transcriptinfo" class="full">
                    <a href="<?php echo $thismedia['pdf'];?>" target="_blank"><button>download PDF of transcript</button></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($thismedia['transcript']): ?>
      <div id="itemtranscript" class="twothirds">
          <?php if ($thismedia['pdf']):?>
              <div class="row">
                  <div id="transcriptinfo" class="full">
                      <h4>Transcript</h4>
                      <a href="<?php echo $thismedia['pdf'];?>" target="_blank"><button>download PDF</button></a>
                  </div>
              </div>
          <?php endif; ?>
          <div class="row">
                  <div class="full">
                      <?php echo $thismedia['transcript'];?>
                  </div>
          </div>
      </div>
    <?php endif; ?>
</div>
<?php   
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues([
        'page' => $page, 
        'perPage' => 25, 
        'resourceProperty' => $property
    ]);
    if ($subjectValues || (!$embedMedia && $itemMedia)):?>
<div class="row">
    <div class="half">
        <?php if (!$embedMedia && $itemMedia): ?>
        <div class="media-list">
            <?php foreach ($itemMedia as $media): ?>
                <?php echo $media->linkPretty(); ?>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="half">
        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<div class="row">
    <div class="full">
        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>
