<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Lora:400,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php if($userBar):
        echo $this->htmlElement('body')->appendAttribute('class', 'hasuser');
    else:
        echo $this->htmlElement('body');
    endif; ?>
        <?php echo $userBar; ?>
        <header>
            <nav>
                <ul id="mobilemenu">
                    <li id="mobilelogo">&nbsp;&nbsp;</li>
                    <li id="mobilebanner"><a href="<?php echo $site->url(); ?>"><?php echo $this->pageTitle($site->title(),0); ?></a></li>
                    <li id="navctl" class="rightctl"><i class="fas fa-bars"></i></li>
                    <li id="searchctl" class="rightctl"><i class="fas fa-search"></i></li>
                </ul>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1,
                    'ulClass' => 'menu closed'
                ]);
                ?>
                <div id="search" class="closed">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
            </nav>
        </header>
        <div id="banner">
            <div class="row">
                <div class="full" id="bannercontent">
                    <h1><a href="<?php echo $site->url(); ?>" id="site-title"><?php echo $this->pageTitle($site->title(),0);?></a></h1>
                    <span class="site-summary secondary-title"><?php echo $site->summary(); ?></span>
                </div>
            </div>
        </div>
        <article>
            <div id="content" role="main"  class="row">
                <div class="full">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </article>
        <footer>
            <div class="footerinfo">
                <div id="footertext">
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                    <?php else: ?>
                        <?php echo $this->translate('Powered by Omeka S'); ?>
                    <?php endif; ?>
                </div>
                <div id="footerlogo">
                    <img src='<?php echo $this->assetUrl('img/dartmouth-college-logo_white.svg');?>' class="footerlogo" alt="Dartmouth College Logo">
                </div>
            </div>
        </footer>
    </body>
</html>
